CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_DETALHES_VENDA" ("VENDA_ID", "ITEM_ID", "CLIENTE", "PRODUTO", "CATEGORIA", "MARCA", "DATA_VENDA", "ANO", "MES", "TOTAL_ITEM") AS 
  SELECT 
  V.ID AS VENDA_ID
  , I.ID AS ITEM_ID
  , C.NOME as CLIENTE
  , P.DESCRICAO AS PRODUTO
  , C.CATEGORIA
  , M.MARCA
  , V.DATA_VENDA
  , TO_CHAR(V.DATA_VENDA, 'YYYY') AS ANO
  , to_char(V.DATA_VENDA, 'MM') AS MES
  , I.TOTAL_ITEM TOTAL_ITEM FROM VENDA V
    LEFT JOIN ITENS I ON I.VENDA_ID = V.ID 
    LEFT JOIN CLIENTE C ON C.ID = V.CLIENTE_ID
    LEFT JOIN PRODUTO P ON P.ID = I.PRODUTO_ID
    LEFT JOIN CATEGORIA C ON C.ID = P.CATEGORIA_ID
    LEFT JOIN MARCAS M ON M.ID = P.MARCA_ID
/

