CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_VENDA" ("ID", "NOME", "DATA_VENDA", "TOTAL_VENDA") AS 
  SELECT 
  V.ID
  ,C.NOME
  , V.DATA_VENDA
  , SUM(NVL(I.TOTAL_ITEM,0)) TOTAL_VENDA FROM VENDA V
    LEFT JOIN ITENS I ON I.VENDA_ID = V.ID 
    LEFT JOIN CLIENTE C ON C.ID = V.CLIENTE_ID
    LEFT JOIN PRODUTO P ON P.ID = I.PRODUTO_ID
  GROUP BY V.ID, C.NOME, V.DATA_VENDA
/

